apiVersion: v1
kind: Secret
metadata:
  name: "postgres-credentials"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
    ai-services.io/component: database
type: Opaque
stringData:
  password: {{ .Values.postgres.password | default "Aiservicesdb@1234" | quote }}

# Made with Bob
