# Builder stage
FROM registry.access.redhat.com/ubi9/ubi:9.8 as builder

ARG VERSION=${VERSION}

# 1. Install heavy build dependencies (gcc, rust, etc.)
RUN dnf -y update && \
    dnf -y install \
        wget \
        patch \
        python3.12 \
        python3.12-pip \
        python3.12-devel \
        gcc \
        gcc-c++ \
        rust \
        cargo \
        openssl-devel \
        zlib-devel && \
    dnf clean all

WORKDIR /build

COPY pre-requirements.txt patches ./

# 2. Install Pre-requistes
RUN python3.12 -m pip install -r pre-requirements.txt \
	--extra-index-url=https://wheels.developerfirst.ibm.com/ppc64le/linux/ \
	--prefer-binary

# 3. Set compiler variables for ppc64le
ENV RUSTC_BOOTSTRAP=1 \
    GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 \
    GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1

# 4. Download litellm & patch it
RUN wget https://github.com/BerriAI/litellm/archive/refs/tags/v${VERSION}.tar.gz >/dev/null
RUN tar -xzf v${VERSION}.tar.gz && \
    cd litellm-${VERSION} && \
    patch -p1 pyproject.toml < ../pyproject-toml.patch && \
    patch -p1 < ../watsonx-passthrough.patch && \
    cp -R ../passthrough litellm/llms/watsonx/ && \
    uv lock && \
# 5. Export dependencies to a requirements.txt file \
    uv export --no-hashes --no-dev \
	--extra proxy \
	--extra semantic-router \
	-o requirements.txt && \
    cat requirements.txt

WORKDIR /build/litellm-${VERSION}

# 6. Compile all dependencies into .whl files
RUN --mount=type=cache,target=/root/.cache/pip \
    python3.12 -m pip wheel -r requirements.txt \
	-w /wheels \
	--extra-index-url=https://wheels.developerfirst.ibm.com/ppc64le/linux/ \
	--prefer-binary && \
    uv build --wheel --out-dir /wheels

# Runtime Stage
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.8

ARG VERSION=${VERSION}

ENV DISABLE_ADMIN_UI=true \
    LITELLM_NON_ROOT=true

RUN --mount=type=bind,from=builder,source=/wheels,target=/wheels,ro \
    microdnf -y update && \
    microdnf -y install \
        python3.12 \
        python3.12-pip && \
    python3.12 -m pip install --no-cache-dir --no-index \
	--find-links=/wheels  \
	litellm[proxy,semantic-router]==${VERSION} && \
    python3.12 -m pip cache purge && \
    microdnf remove -y python3.12-pip && \
    microdnf clean all 

USER 1001

WORKDIR /app

COPY config ./

EXPOSE 4000

# Start the proxy
CMD ["litellm", "--port", "4000"]
