{{- if .Values.instruct.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: "vllm-instruct-api-key"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
type: Opaque
stringData:
  apiKey: {{ .Values.instruct.apiKey | quote }}
{{- end }}
