FROM registry.access.redhat.com/ubi9/ubi:9.7 as tools_builder

ARG DNF_FLAGS="--disablerepo=* --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms"

ENV VIRTUAL_ENV=/opt/venv

COPY requirements.txt requirements.txt

RUN dnf update ${DNF_FLAGS} -y \
  && dnf install ${DNF_FLAGS} -y gcc \
  python3.12-pip python3.12 python3.12-devel python3-pexpect python3-ptyprocess python3-pyyaml python3-file-magic \
  && python3.12 -m venv ${VIRTUAL_ENV} \
  && source ${VIRTUAL_ENV}/bin/activate \
  && pip3.12 install -r requirements.txt \
  && rm -rf /var/cache/dnf && dnf clean all -y

FROM registry.access.redhat.com/ubi9/ubi:9.7

ARG SR_VERSION
ARG DNF_FLAGS="--disablerepo=* --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms"

COPY --from=tools_builder /opt/venv /opt/venv

RUN curl -o ServiceReport-${SR_VERSION}.ppc64le.rpm https://public.dhe.ibm.com/software/server/POWER/Linux/yum/OSS/RHEL/9/ppc64le/ServiceReport-${SR_VERSION}.ppc64le.rpm \
  && dnf install ${DNF_FLAGS} -y kmod sos python3.12 \
  ServiceReport-${SR_VERSION}.ppc64le.rpm \
  && rm -rf /var/cache/dnf && dnf clean all -y

ENV VIRTUAL_ENV=/opt/venv
ENV PATH=${VIRTUAL_ENV}/bin:$PATH
